### ISSUE TITLE
Can we use this code with esp8266 ?

### ISSUE THREAD

**Issue by EMMechanics** [chinchillajared/arduino-with-twilio#1]
Thank you for sharing this code, could you please indicate the required modifications to make it works with esp8266.
Thanks

**Comment by chinchillajared** [comment]
Hello EMMechanics,

Right now I am working, once I have time I will answer your question, there is a library called Twilio-esp32-client that you can use for that, but for esp8266 you need to make some changes.

https://github.com/ademuri/twilio-esp32-client

**Comment by chinchillajared** [comment]
> Thank you for sharing this code, could you please indicate the required modifications to make it works with esp8266. Thanks

When I first started working on this project it was meant to work with ESP8266 but I was using the Wemos version which doesn't have enough cache memory to make a POST request like the one in the code, I will be working on a version for ESP8266 as from now there is only one version for ESP32 that works "only in ESP32", once I have an update I will let you know.

**Comment by EMMechanics** [comment]
Thank you so much, and I appreciate your work and efforts. I am also working with wemos d1 mini, I tried with callme bot service, but after a few days, it started showing messages asking for support with every received WhatsApp message, so I preferred to work with Twilio. It is free with the first 1000 messages monthly, which is more than enough.
Thanks and regards

**Comment by chinchillajared** [comment]
> Thank you so much, and I appreciate your work and efforts. I am also working with wemos d1 mini, I tried with callme bot service, but after a few days, it started showing messages asking for support with every received WhatsApp message, so I preferred to work with Twilio. It is free with the first 1000 messages monthly, which is more than enough. Thanks and regards

Hello EMMechanics,

Finally, I was able to create a version that works with ESP8266, the current release will send either Whatsapp or SMS depending on the configuration, due to the limited amount of memory in the ESP8266 boards, the post request or the entire code takes too much space causing an overflow memory problem that makes the board run on a restart loop, the code still working but you may get messages every 2s, I still working to reduce the memory and fix this problem. Any suggestions and feedback are more than welcome.

You can find the repository with the link below:

https://github.com/chinchillajared/esp8266-with-twilio

Best regards 
Jared

**Comment by chinchillajared** [comment]
I will consider this issue fixed as it is not directly related to the code of the repository.

**Comment by EMMechanics** [comment]
Thank you very much, your help is highly appreciated.
